import { faAndroid, faApple } from "@fortawesome/free-brands-svg-icons";
import {
  faBuilding,
  faCartShopping,
  faGlobe,
  faColumns,
  faSearch,
  faEnvelope,
  faHandHoldingUsd,
  faChartLine,
  faBullhorn,
  faMobile,
  faVideo,
  faMapMarkerAlt,
  faShoppingCart,
  faCog,
  faRetweet,
  faPrint,
  faLaptop,
  faBox,
  faFileAlt,
  faFlag,
  faPalette,
  faChartBar,
  faImage,
  faBook,
  faTshirt,
  faMapSigns,
  faShapes,
  faCamera,
  faFileSignature,
  faMapMarker,
  faBookOpen,
  faSignature,
  faCommentAlt,
  faHandHoldingHeart,
  faSyncAlt,
  faChartPie,
  faDesktop,
  faCogs,
  faMicrophone,
  faTv,
  faGamepad,
  faDraftingCompass,
  faCheckCircle,
  faWrench,
  faShieldAlt,
  faDollarSign,
  faSearch as faSearchAlt,
  faShoppingBag,
  faTools,
  faCalculator,
  faFileInvoice,
  faBlog,
  faInfoCircle,
  faBriefcase,
  faPhone,
  faCreditCard,
  faRightToBracket,
  faUsers,
  faGaugeHigh,
  faMousePointer,
  faShareNodes,
  faFileLines,
  faMobileScreen,
  faSmile,
  faPenNib,
  faIdBadge,
  faLandmark,
  faScroll,
  faCakeCandles,
  faMusic,
  faGraduationCap,
  faSchool,
  faUtensils,
  faWineGlass,
  faDumbbell,
  faChalkboardTeacher,
  faHeart,
  faBaby,
  faHouse,
  faUserTie,
  faLock,
  faGlassCheers,
  faChampagneGlasses,
  faMasksTheater,
  faGlassMartiniAlt,
  faWater,
  faChalkboard,
  faMicrophoneLines,
  faAward,
  faTag,
  faPlaneDeparture,
  faLightbulb,
  faPuzzlePiece,
  faCalendarCheck,
  faPeopleGroup,
  faChildReaching,
  faRing,
  faPeopleArrows,
  faStar,
  faTrain,
  faBus,
  faTruck,
  faTaxi,
  faStore,
  faAd,
  faNewspaper,
  faRadio,
  faFilm,
  faIdCard,
  faSitemap,
  faProjectDiagram,
  faImages,
  faCalendarAlt,
  faFolderOpen,
  faSearchDollar,
  faHashtag,
  faUserFriends,
  faBullseye,
} from "@fortawesome/free-solid-svg-icons";

export const weddingplannersLink = [
  {
    category: "Wedding Planning",
    links: [
      {
        path: "/services/wedding-planners/destination-wedding",
        title: "Destination Wedding Arrangements & Planning",
        icon: faGlobe,
      },
      {
        path: "/services/wedding-planners/ring-ceremony",
        title: "Ring Ceremony (Engagements)",
        icon: faRing,
      },
      {
        path: "/services/wedding-planners/wedding-planners",
        title: "Wedding Planners",
        icon: faPeopleArrows,
      },
      {
        path: "/services/wedding-planners/receptions",
        title: "Receptions",
        icon: faChampagneGlasses,
      },
      {
        path: "/services/wedding-planners/mehendi",
        title: "Mehendi",
        icon: faPalette,
      },
      {
        path: "/services/wedding-planners/sangeet",
        title: "Sangeet",
        icon: faMusic,
      },
    ],
  },
  {
    category: "Wedding Services",
    links: [
      {
        path: "/services/wedding-planners/entertainment-and-artists",
        title: "Entertainment & Artists",
        icon: faMicrophone,
      },
      {
        path: "/services/wedding-planners/hospitality",
        title: "Hospitality",
        icon: faUtensils,
      },
      {
        path: "/services/wedding-planners/guest-management",
        title: "Guest Management",
        icon: faUsers,
      },
      {
        path: "/services/wedding-planners/photography-and-videography",
        title: "Photography & Videography",
        icon: faCamera,
      },
      {
        path: "/services/wedding-planners/theme-decors",
        title: "Theme Decors",
        icon: faShapes,
      },
    ],
  },
  {
    category: "Personal & Cultural",
    links: [
      {
        path: "/services/wedding-planners/birthday-parties",
        title: "Birthday Parties",
        icon: faCakeCandles,
      },
      {
        path: "/services/wedding-planners/personal-celebrations",
        title: "Personal Celebrations",
        icon: faGlassCheers,
      },
      {
        path: "/services/wedding-planners/cultural-events",
        title: "Cultural Events",
        icon: faMasksTheater,
      },
    ],
  },
  {
    category: "Corporate & Public",
    links: [
      {
        path: "/services/wedding-planners/product-launches",
        title: "Product Launches",
        icon: faBullhorn,
      },
      {
        path: "/services/wedding-planners/concert-and-gigs",
        title: "Concert & Gigs",
        icon: faMusic,
      },
      {
        path: "/services/wedding-planners/protocol-events",
        title: "Protocol Events",
        icon: faBriefcase,
      },
      {
        path: "/services/wedding-planners/fashion-shows",
        title: "Fashion Shows",
        icon: faUserTie,
      },
      {
        path: "/services/wedding-planners/award-nights",
        title: "Award Nights",
        icon: faAward,
      },
      {
        path: "/services/wedding-planners/carnivals",
        title: "Carnivals",
        icon: faMasksTheater,
      },
      {
        path: "/services/wedding-planners/brand-promotional-events",
        title: "Brand Promotional Events",
        icon: faBullseye,
      },
      {
        path: "/services/wedding-planners/celeb-artist-management",
        title: "Celeb/Artist Management",
        icon: faStar,
      },
      {
        path: "/services/wedding-planners/corporate-seminars",
        title: "Corporate Seminars & Work Shops",
        icon: faChalkboard,
      },
      {
        path: "/services/wedding-planners/exhibitions",
        title: "Exhibitions",
        icon: faBuilding,
      },
    ],
  },
];

export const digitalMarketingLinks = [
  {
    category: "Digital Strategy & Core",
    links: [
      { path: "/services/digital-media-marketing/digital-marketing", title: "Digital Marketing", icon: faBullhorn },
      { path: "/services/digital-media-marketing/digital-strategy-consulting", title: "Digital Strategy Consulting", icon: faLightbulb },
      { path: "/services/digital-media-marketing/digital-media-buying", title: "Digital Media Buying", icon: faSearchDollar },
      { path: "/services/digital-media-marketing/online-pr", title: "Online PR", icon: faUsers },
      { path: "/services/digital-media-marketing/social-media-digital-campaign", title: "Social Media & Digital Campaign", icon: faHashtag },
      { path: "/services/digital-media-marketing/search-engine-optimization", title: "Search Engine Optimization", icon: faSearch },
      { path: "/services/digital-media-marketing/affiliate-marketing", title: "Affiliate Marketing", icon: faHandHoldingUsd },
      { path: "/services/digital-media-marketing/influence-marketing", title: "Influence Marketing", icon: faUserFriends },
      { path: "/services/digital-media-marketing/ppc", title: "PPC", icon: faMousePointer },
      { path: "/services/digital-media-marketing/content-marketing", title: "Content Marketing", icon: faFileLines },
      { path: "/services/digital-media-marketing/social-media-management", title: "Social Media Management", icon: faShareNodes },
    ],
  },
  {
    category: "Creative & Video Media",
    links: [
      { path: "/services/digital-media-marketing/digital-creative-media", title: "Digital Creative Media", icon: faPalette },
      { path: "/services/digital-media-marketing/tvc-ad-film-making", title: "TVC/AD Film Making", icon: faFilm },
      { path: "/services/digital-media-marketing/digital-commercials", title: "Digital Commercials", icon: faVideo },
      { path: "/services/digital-media-marketing/web-commercials", title: "Web Commercials", icon: faGlobe },
      { path: "/services/digital-media-marketing/product-services-explanatory-videos", title: "Product & Services Explanatory Videos", icon: faFileSignature },
      { path: "/services/digital-media-marketing/company-profile-videos", title: "Company Profile Videos", icon: faIdCard },
      { path: "/services/digital-media-marketing/customer-testimonial-videos", title: "Customer Testimonial Videos", icon: faCommentAlt },
      { path: "/services/digital-media-marketing/company-corporate-film", title: "Company Corporate Film", icon: faBuilding },
      { path: "/services/digital-media-marketing/product-photo-videography", title: "Product Photo & Videography", icon: faCamera },
      { path: "/services/digital-media-marketing/multi-channel-networking", title: "Multi-channel Networking", icon: faSitemap },
      { path: "/services/digital-media-marketing/youtube-entertainment", title: "Youtube Entertainment", icon: faTv },
    ],
  },
];


export const brandingLinks = [
  {
    category: "Brand Strategy & Identity",
    links: [
      { path: "/services/branding/brand-audit", title: "Brand Audit", icon: faSearch },
      { path: "/services/branding/brand-strategy", title: "Brand Strategy", icon: faLightbulb },
      { path: "/services/branding/brand-identity", title: "Brand Identity", icon: faIdBadge },
      { path: "/services/branding/brand-positioning", title: "Brand Positioning", icon: faMapMarker },
      { path: "/services/branding/brand-activations", title: "Brand Activations", icon: faBullseye },
      { path: "/services/branding/infilm-branding", title: "Infilm Branding", icon: faFilm },
      { path: "/services/branding/corporate-branding", title: "Corporate Branding", icon: faBuilding },
    ],
  },
  {
    category: "Brand Designing",
    links: [
      { path: "/services/branding/social-media-creatives", title: "Social Media Creatives", icon: faImages },
      { path: "/services/branding/posters", title: "Posters", icon: faImage },
      { path: "/services/branding/labeling", title: "Labeling", icon: faTag },
      { path: "/services/branding/calendars", title: "Calendars", icon: faCalendarAlt },
      { path: "/services/branding/folders", title: "Folders", icon: faFolderOpen },
      { path: "/services/branding/diaries", title: "Diaries", icon: faBook },
      { path: "/services/branding/bulletin", title: "Bulletin", icon: faNewspaper },
      { path: "/services/branding/booklets", title: "Booklets", icon: faBookOpen },
      { path: "/services/branding/catalogue", title: "Catalogue", icon: faFileAlt },
      { path: "/services/branding/brochure", title: "Brochure", icon: faBook },
      { path: "/services/branding/leaflets", title: "Leaflets", icon: faFileLines },
    ],
  },
];

export const advertisingLinks = [
  {
    category: "ATL/OOH Advertisement",
    links: [
      { path: "/services/advertisement/display-boards", title: "Display Boards", icon: faAd },
      { path: "/services/advertisement/bill-boards", title: "Bill Boards", icon: faAd },
      { path: "/services/advertisement/unipole", title: "Unipole", icon: faAd },
      { path: "/services/advertisement/wall-panel", title: "Wall Panel", icon: faAd },
      { path: "/services/advertisement/over-head-panel", title: "Over Head Panel", icon: faAd },
      { path: "/services/advertisement/building-wraps", title: "Building Wraps", icon: faBuilding },
      { path: "/services/advertisement/bus-shelters", title: "Bus Shelters", icon: faBus },
      { path: "/services/advertisement/flyover-pillars", title: "Flyover Pillars", icon: faLandmark },
      { path: "/services/advertisement/malls", title: "Malls", icon: faStore },
      { path: "/services/advertisement/railway-stations", title: "Railway Stations", icon: faTrain },
      { path: "/services/advertisement/airports", title: "Airports", icon: faPlaneDeparture },
    ],
  },
  {
    category: "Transit Media",
    links: [
      { path: "/services/advertisement/cab-branding", title: "Cab Branding", icon: faTaxi },
      { path: "/services/advertisement/bus-panels", title: "Bus Panels", icon: faBus },
      { path: "/services/advertisement/bus-wraps", title: "Bus Wraps", icon: faBus },
      { path: "/services/advertisement/mobile-display-vans", title: "Mobile Display Vans", icon: faTruck },
      { path: "/services/advertisement/local-metro-trains", title: "Local & Metro Trains", icon: faTrain },
      { path: "/services/advertisement/truck-wrap", title: "Truck Wrap", icon: faTruck },
      { path: "/services/advertisement/auto-rickshaw-branding", title: "Auto Rickshaw Branding", icon: faTaxi },
    ],
  },
  {
    category: "Strategic Format",
    links: [
      { path: "/services/advertisement/pole-kiosk", title: "Pole Kiosk", icon: faAd },
      { path: "/services/advertisement/metro-kiosk", title: "Metro Kiosk", icon: faTrain },
      { path: "/services/advertisement/college-kiosk", title: "College Kiosk", icon: faGraduationCap },
      { path: "/services/advertisement/bench-branding", title: "Bench Branding", icon: faUsers },
      { path: "/services/advertisement/barcodes", title: "Barcodes", icon: faSearch },
      { path: "/services/advertisement/airport-trolley", title: "Airport Trolley", icon: faPlaneDeparture },
      { path: "/services/advertisement/hypermarts", title: "Hypermarts", icon: faShoppingCart },
      { path: "/services/advertisement/event-advertising", title: "Event Advertising", icon: faPeopleArrows },
    ],
  },
  {
    category: "Print Media",
    links: [
      { path: "/services/advertisement/newspapers", title: "Newspapers", icon: faNewspaper },
      { path: "/services/advertisement/magazines", title: "Magazines", icon: faBookOpen },
      { path: "/services/advertisement/periodicals", title: "Periodicals", icon: faFileAlt },
      { path: "/services/advertisement/news-letters", title: "News Letters", icon: faEnvelope },
      { path: "/services/advertisement/digital-media-buying", title: "Digital Media Buying", icon: faSearchDollar },
    ],
  },
  {
    category: "Electronic Media",
    links: [
      { path: "/services/advertisement/theater", title: "Theater", icon: faFilm },
      { path: "/services/advertisement/televisions", title: "Televisions", icon: faTv },
      { path: "/services/advertisement/infilm", title: "Infilm", icon: faVideo },
      { path: "/services/advertisement/radio", title: "Radio", icon: faRadio },
    ],
  },
  {
    category: "BTL Advertisement",
    links: [
      { path: "/services/advertisement/brand-promotions", title: "Brand Promotions", icon: faBullhorn },
      { path: "/services/advertisement/road-shows", title: "Road Shows", icon: faTruck },
      { path: "/services/advertisement/experiential-marketing", title: "Experiential Marketing", icon: faLightbulb },
      { path: "/services/advertisement/mall-activities", title: "Mall Activities", icon: faStore },
      { path: "/services/advertisement/retail-store-activities", title: "Retail Store Activities", icon: faShoppingCart },
      { path: "/services/advertisement/direct-marketing", title: "Direct Marketing", icon: faEnvelope },
      { path: "/services/advertisement/digital-marketing-btl", title: "Digital Marketing", icon: faGlobe },
      { path: "/services/advertisement/tele-marketing", title: "Tele Marketing", icon: faPhone },
    ],
  },
];

export const eventsLinks = [
  {
    category: "Corporate Events",
    links: [
      { path: "/events/corporate-meetings", title: "Corporate Meetings", icon: faWater },
      { path: "/events/conferences-seminars", title: "Conferences & Seminars", icon: faChalkboard },
      { path: "/events/product-launch-events", title: "Product Launch Events", icon: faBullhorn },
      { path: "/events/award-functions", title: "Award Functions", icon: faAward },
      { path: "/events/team-outings", title: "Team Outings", icon: faUsers },
      { path: "/events/annual-day-celebrations", title: "Annual Day Celebrations", icon: faCalendarCheck },
      { path: "/events/employee-engagement-events", title: "Employee Engagement Events", icon: faSmile },
    ],
  },
  {
    category: "Entertainment Events",
    links: [
      { path: "/events/celebrity-management", title: "Celebrity Management", icon: faStar },
      { path: "/events/live-concerts", title: "Live Concerts", icon: faMicrophoneLines },
      { path: "/events/dj-nights", title: "DJ Nights", icon: faMusic },
      { path: "/events/fashion-shows", title: "Fashion Shows", icon: faUserTie },
      { path: "/events/cultural-events", title: "Cultural Events", icon: faMasksTheater },
      { path: "/events/college-fest-events", title: "College Fest Events", icon: faSchool },
    ],
  },
  {
    category: "Promotional Events",
    links: [
      { path: "/events/brand-promotions", title: "Brand Promotions", icon: faBullseye },
      { path: "/events/mall-activations", title: "Mall Activations", icon: faStore },
      { path: "/events/road-shows", title: "Road Shows", icon: faTruck },
      { path: "/events/store-launches", title: "Store Launches", icon: faStore },
      { path: "/events/political-campaign-events", title: "Political Campaign Events", icon: faFlag },
      { path: "/events/public-relation-events", title: "Public Relation Events", icon: faCommentAlt },
    ],
  },
  {
    category: "Exhibition & Trade Shows",
    links: [
      { path: "/events/exhibition-stall-design", title: "Exhibition Stall Design", icon: faDraftingCompass },
      { path: "/events/trade-show-management", title: "Trade Show Management", icon: faSitemap },
      { path: "/events/expo-promotions", title: "Expo Promotions", icon: faImages },
    ],
  },
  {
    category: "Religious & Traditional Events",
    links: [
      { path: "/events/pooja-events", title: "Pooja Events", icon: faWater },
      { path: "/events/temple-festivals", title: "Temple Festivals", icon: faLandmark },
      { path: "/events/traditional-ceremonies", title: "Traditional Ceremonies", icon: faScroll },
    ],
  },
];
