import React from "react";
import { Helmet } from "react-helmet-async";
import shippinganddelivery from "../../assets/Thumbnails.png";

const title = "Privacy Policy | Leor Media";
const description =
  "Read Leor Media's Privacy Policy to understand how we collect, use, and protect your personal information when using our services.";
const keywords =
  "privacy policy, Leor Media, data protection, personal information, Visakhapatnam digital agency, user privacy, data security";
const ogImage = shippinganddelivery;
const canonical = "https://leormedia.com/Legal/privacy-policy";

const PrivacyPolicy = () => {
  return (
    <>
      <Helmet>
        <title>{title}</title>
        <meta name="description" content={description} />
        <meta name="keywords" content={keywords} />
        <meta name="robots" content="index, follow" />
        <meta name="author" content="Leor Media" />
        <meta name="language" content="en" />
        <meta name="distribution" content="global" />

        {/* Open Graph / Facebook */}
        <meta property="og:title" content={title} />
        <meta property="og:description" content={description} />
        <meta property="og:image" content={ogImage} />
        <meta property="og:url" content={canonical} />
        <meta property="og:type" content="website" />

        {/* Twitter */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content={title} />
        <meta name="twitter:description" content={description} />
        <meta name="twitter:image" content={ogImage} />

        {/* Canonical Link */}
        <link rel="canonical" href={canonical} />
      </Helmet>

      <div className="privacypolicy px-5 text-black mx-4 leading-relaxed">
        <h1 className="text-center py-10 font-bold text-3xl pt-20 text-black">
          PRIVACY POLICY
        </h1>
        <p className="text-sm text-gray-500 mb-6">Effective date: June 2026</p>

        <h2 className="font-bold text-xl mt-6 mb-2">1. INTRODUCTION</h2>
        <p className="mb-4">
          Welcome to Leor Media. We operate{" "}
          <a href="https://leormedia.com" className="text-primary hover:underline">
            https://leormedia.com
          </a>{" "}
          (hereinafter referred to as “Service”). Our Privacy Policy governs your visit to our website, and explains how we collect, safeguard, and disclose information that results from your use of our Service.
        </p>
        <p className="mb-4">
          We use your data to provide and improve our services. By using the Service, you agree to the collection and use of information in accordance with this policy.
        </p>

        <h2 className="font-bold text-xl mt-6 mb-2">2. DEFINITIONS</h2>
        <ul className="list-disc list-inside mb-4 pl-4 space-y-2">
          <li>
            <strong>SERVICE</strong> means the https://leormedia.com website operated by Leor Media.
          </li>
          <li>
            <strong>PERSONAL DATA</strong> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
          </li>
          <li>
            <strong>USAGE DATA</strong> is data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
          </li>
          <li>
            <strong>COOKIES</strong> are small files stored on your device (computer or mobile device).
          </li>
        </ul>

        <h2 className="font-bold text-xl mt-6 mb-2">3. INFORMATION COLLECTION AND USE</h2>
        <p className="mb-4">
          We collect several different types of information for various purposes to provide and improve our services to you, including when you contact us for quotes, consult with our AI chatbot, or inquire about event planning.
        </p>

        <h2 className="font-bold text-xl mt-6 mb-2">4. TYPES OF DATA COLLECTED</h2>
        <h3 className="font-semibold text-lg mt-4 mb-1">Personal Data</h3>
        <p className="mb-2">
          While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include:
        </p>
        <ul className="list-disc list-inside mb-4 pl-4 space-y-1">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
          <li>Event Details (for quotation purposes)</li>
          <li>Cookies and Usage Data</li>
        </ul>

        <h3 className="font-semibold text-lg mt-4 mb-1">Usage Data</h3>
        <p className="mb-4">
          We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device. This may include your IP address, browser type, pages visited, time spent, and diagnostic data.
        </p>

        <h2 className="font-bold text-xl mt-6 mb-2">5. USE OF DATA</h2>
        <p className="mb-2">Leor Media uses the collected data for various purposes:</p>
        <ul className="list-disc list-inside mb-4 pl-4 space-y-2">
          <li>To provide and maintain our Service;</li>
          <li>To notify you about changes to our Service;</li>
          <li>To provide customer support;</li>
          <li>To gather analysis or valuable information so that we can improve our Service;</li>
          <li>To monitor the usage of our Service;</li>
          <li>To process event booking and service quotation requests;</li>
          <li>To support client communication through our AI Chatbot;</li>
          <li>To fulfill obligations and enforce rights arising from contracts entered between you and us, including billing.</li>
        </ul>

        <h2 className="font-bold text-xl mt-6 mb-2">6. RETENTION & TRANSFER OF DATA</h2>
        <p className="mb-4">
          We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy.
        </p>
        <p className="mb-4">
          Your information, including Personal Data, may be transferred to – and maintained on – computers located in MVP Colony, Visakhapatnam, Andhra Pradesh, India. Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer. Leor Media will take all steps reasonably necessary to ensure that your data is treated securely.
        </p>

        <h2 className="font-bold text-xl mt-6 mb-2">7. DATA PROTECTION RIGHTS</h2>
        <p className="mb-4">
          Depending on your location, you may have specific data protection rights regarding your personal information, including the right to access, update, delete, or restrict the use of your Personal Data. If you wish to be informed of what Personal Data we hold about you or want it removed from our systems, please email us at{" "}
          <a href="mailto:leormedia@gmail.com" className="text-primary hover:underline">
            leormedia@gmail.com
          </a>
          .
        </p>

        <h2 className="font-bold text-xl mt-6 mb-2">8. SECURITY OF DATA</h2>
        <p className="mb-4">
          The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
        </p>

        <h2 className="font-bold text-xl mt-6 mb-2">9. BEHAVIORAL REMARKETING</h2>
        <p className="mb-4">
          We may use remarketing services to advertise on third-party websites to you after you visited our Service. We and our third-party vendors use cookies to optimize and serve ads based on your past visits to our website.
        </p>

        <h2 className="font-bold text-xl mt-8 mb-2">10. CONTACT US</h2>
        <p className="mb-6">
          If you have any questions about this Privacy Policy, please contact us by email at:{" "}
          <a href="mailto:leormedia@gmail.com" className="text-primary hover:underline font-semibold">
            leormedia@gmail.com
          </a>
          .
        </p>
      </div>
    </>
  );
};

export default PrivacyPolicy;
